# Netlify Production Configuration
[build]
  # Build command
  command = "npm run build:production"
  
  # Output directory
  publish = "dist"
  
  # Environment
  NODE_ENV = "production"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  
  # NPM version
  NPM_VERSION = "8"

# Redirects and Rewrites for SPA
[[redirects]]
  # Health check endpoint
  from = "/health"
  to = "/health"
  status = 200

[[redirects]]
  # API health check
  from = "/api/health"
  to = "/.netlify/functions/health"
  status = 200

[[redirects]]
  # Handle client-side routing
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://esm.sh; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://generativelanguage.googleapis.com; media-src 'self' blob:; worker-src 'self' blob:"
    
    # Performance headers
    Cache-Control = "public, max-age=31536000"

# Static assets optimization
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# HTML files should not be cached aggressively
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Compression
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true
